//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaraPayamak.ReceiveSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiveSms.ReceiveSoap")]
    public interface ReceiveSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetInboxCount(string username, string password, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetInboxCountAsync(string username, string password, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutBoxCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetOutBoxCount(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutBoxCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetOutBoxCountAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MessagesBL[] GetMessages(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesAsync(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesWithChangeIsRead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesWithChangeIsRead(string username, string password, int location, string from, int index, int count, bool isRead, bool changeIsRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesWithChangeIsRead", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesWithChangeIsReadAsync(string username, string password, int location, string from, int index, int count, bool isRead, bool changeIsRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeMessageIsRead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int ChangeMessageIsRead(string username, string password, string msgIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeMessageIsRead", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChangeMessageIsReadAsync(string username, string password, string msgIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesByDateAsync(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesFilterByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesFilterByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesFilterByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesFilterByDateAsync(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersMessagesByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MessagesBL[] GetUsersMessagesByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersMessagesByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetUsersMessagesByDateAsync(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        string GetMessageStr(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageStr", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMessageStrAsync(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveMessages(string username, string password, FaraPayamak.ReceiveSms.MessageLocation location, string msgIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveMessagesAsync(string username, string password, FaraPayamak.ReceiveSms.MessageLocation location, string msgIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveMessages2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveMessages2(string username, string password, int location, string msgIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveMessages2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveMessages2Async(string username, string password, int location, string msgIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesReceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MsgReceptions[] GetMessagesReceptions(string username, string password, int msgId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesReceptions", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MsgReceptions[]> GetMessagesReceptionsAsync(string username, string password, int msgId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesAfterID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesAfterID(string username, string password, int location, string from, int count, int msgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesAfterID", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesAfterIDAsync(string username, string password, int location, string from, int count, int msgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesAfterIDJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        string GetMessagesAfterIDJson(string username, string password, int location, string from, int count, int msgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesAfterIDJson", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMessagesAfterIDJsonAsync(string username, string password, int location, string from, int count, int msgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestReceiveMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ReceiveSms.LatestMsgReport GetLatestReceiveMsg(string username, string password, string sender, string receiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestReceiveMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.LatestMsgReport> GetLatestReceiveMsgAsync(string username, string password, string sender, string receiver);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagesBL : BaseBL {
        
        private long msgIDField;
        
        private int userIDField;
        
        private int linkIDField;
        
        private int numberIDField;
        
        private double tariffField;
        
        private byte msgTypeField;
        
        private string bodyField;
        
        private string udhField;
        
        private System.DateTime sendDateField;
        
        private string senderField;
        
        private string receiverField;
        
        private int firstLocationField;
        
        private int currentLocationField;
        
        private int partsField;
        
        private bool isFlashField;
        
        private bool isReadField;
        
        private bool isUnicodeField;
        
        private double creditField;
        
        private int moduleField;
        
        private int recCountField;
        
        private int recFailedField;
        
        private int recSuccessField;
        
        private bool isMoneyBackField;
        
        private int userStepedMasterField;
        
        private int userMasterField;
        
        private int moneyBackCountField;
        
        private int moneyBackLevelField;
        
        private System.Nullable<bool> autoSpeechTextField;
        
        private System.Nullable<int> shareServiceBodyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LinkID {
            get {
                return this.linkIDField;
            }
            set {
                this.linkIDField = value;
                this.RaisePropertyChanged("LinkID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NumberID {
            get {
                return this.numberIDField;
            }
            set {
                this.numberIDField = value;
                this.RaisePropertyChanged("NumberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
                this.RaisePropertyChanged("Tariff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("MsgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Udh {
            get {
                return this.udhField;
            }
            set {
                this.udhField = value;
                this.RaisePropertyChanged("Udh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int FirstLocation {
            get {
                return this.firstLocationField;
            }
            set {
                this.firstLocationField = value;
                this.RaisePropertyChanged("FirstLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CurrentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
                this.RaisePropertyChanged("CurrentLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsFlash {
            get {
                return this.isFlashField;
            }
            set {
                this.isFlashField = value;
                this.RaisePropertyChanged("IsFlash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsRead {
            get {
                return this.isReadField;
            }
            set {
                this.isReadField = value;
                this.RaisePropertyChanged("IsRead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsUnicode {
            get {
                return this.isUnicodeField;
            }
            set {
                this.isUnicodeField = value;
                this.RaisePropertyChanged("IsUnicode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("Credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("Module");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RecCount {
            get {
                return this.recCountField;
            }
            set {
                this.recCountField = value;
                this.RaisePropertyChanged("RecCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int RecFailed {
            get {
                return this.recFailedField;
            }
            set {
                this.recFailedField = value;
                this.RaisePropertyChanged("RecFailed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int RecSuccess {
            get {
                return this.recSuccessField;
            }
            set {
                this.recSuccessField = value;
                this.RaisePropertyChanged("RecSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool IsMoneyBack {
            get {
                return this.isMoneyBackField;
            }
            set {
                this.isMoneyBackField = value;
                this.RaisePropertyChanged("IsMoneyBack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int UserStepedMaster {
            get {
                return this.userStepedMasterField;
            }
            set {
                this.userStepedMasterField = value;
                this.RaisePropertyChanged("UserStepedMaster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int UserMaster {
            get {
                return this.userMasterField;
            }
            set {
                this.userMasterField = value;
                this.RaisePropertyChanged("UserMaster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int MoneyBackCount {
            get {
                return this.moneyBackCountField;
            }
            set {
                this.moneyBackCountField = value;
                this.RaisePropertyChanged("MoneyBackCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int MoneyBackLevel {
            get {
                return this.moneyBackLevelField;
            }
            set {
                this.moneyBackLevelField = value;
                this.RaisePropertyChanged("MoneyBackLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<bool> AutoSpeechText {
            get {
                return this.autoSpeechTextField;
            }
            set {
                this.autoSpeechTextField = value;
                this.RaisePropertyChanged("AutoSpeechText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ShareServiceBodyID {
            get {
                return this.shareServiceBodyIDField;
            }
            set {
                this.shareServiceBodyIDField = value;
                this.RaisePropertyChanged("ShareServiceBodyID");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagesBL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LatestMsgReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long msgIDField;
        
        private string bodyField;
        
        private int partsField;
        
        private System.DateTime sendDateField;
        
        private string senderField;
        
        private string receiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgReceptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recNumberField;
        
        private string sendDateField;
        
        private string recStatusField;
        
        private string deliveryStatusField;
        
        private string recIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecNumber {
            get {
                return this.recNumberField;
            }
            set {
                this.recNumberField = value;
                this.RaisePropertyChanged("RecNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecStatus {
            get {
                return this.recStatusField;
            }
            set {
                this.recStatusField = value;
                this.RaisePropertyChanged("RecStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
                this.RaisePropertyChanged("DeliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MessageLocation {
        
        /// <remarks/>
        Received,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Removed,
        
        /// <remarks/>
        Deleted,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceiveSoapChannel : FaraPayamak.ReceiveSms.ReceiveSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveSoapClient : System.ServiceModel.ClientBase<FaraPayamak.ReceiveSms.ReceiveSoap>, FaraPayamak.ReceiveSms.ReceiveSoap {
        
        public ReceiveSoapClient() {
        }
        
        public ReceiveSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetInboxCount(string username, string password, bool isRead) {
            return base.Channel.GetInboxCount(username, password, isRead);
        }
        
        public System.Threading.Tasks.Task<int> GetInboxCountAsync(string username, string password, bool isRead) {
            return base.Channel.GetInboxCountAsync(username, password, isRead);
        }
        
        public int GetOutBoxCount(string username, string password) {
            return base.Channel.GetOutBoxCount(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetOutBoxCountAsync(string username, string password) {
            return base.Channel.GetOutBoxCountAsync(username, password);
        }
        
        public FaraPayamak.ReceiveSms.MessagesBL[] GetMessages(string username, string password, int location, string from, int index, int count) {
            return base.Channel.GetMessages(username, password, location, from, index, count);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesAsync(string username, string password, int location, string from, int index, int count) {
            return base.Channel.GetMessagesAsync(username, password, location, from, index, count);
        }
        
        public FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesWithChangeIsRead(string username, string password, int location, string from, int index, int count, bool isRead, bool changeIsRead) {
            return base.Channel.GetMessagesWithChangeIsRead(username, password, location, from, index, count, isRead, changeIsRead);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesWithChangeIsReadAsync(string username, string password, int location, string from, int index, int count, bool isRead, bool changeIsRead) {
            return base.Channel.GetMessagesWithChangeIsReadAsync(username, password, location, from, index, count, isRead, changeIsRead);
        }
        
        public int ChangeMessageIsRead(string username, string password, string msgIds) {
            return base.Channel.ChangeMessageIsRead(username, password, msgIds);
        }
        
        public System.Threading.Tasks.Task<int> ChangeMessageIsReadAsync(string username, string password, string msgIds) {
            return base.Channel.ChangeMessageIsReadAsync(username, password, msgIds);
        }
        
        public FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetMessagesByDate(username, password, location, from, index, count, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesByDateAsync(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetMessagesByDateAsync(username, password, location, from, index, count, dateFrom, dateTo);
        }
        
        public FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesFilterByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo, bool isRead) {
            return base.Channel.GetMessagesFilterByDate(username, password, location, from, index, count, dateFrom, dateTo, isRead);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesFilterByDateAsync(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo, bool isRead) {
            return base.Channel.GetMessagesFilterByDateAsync(username, password, location, from, index, count, dateFrom, dateTo, isRead);
        }
        
        public FaraPayamak.ReceiveSms.MessagesBL[] GetUsersMessagesByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetUsersMessagesByDate(username, password, location, from, index, count, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetUsersMessagesByDateAsync(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetUsersMessagesByDateAsync(username, password, location, from, index, count, dateFrom, dateTo);
        }
        
        public string GetMessageStr(string username, string password, int location, string from, int index, int count) {
            return base.Channel.GetMessageStr(username, password, location, from, index, count);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageStrAsync(string username, string password, int location, string from, int index, int count) {
            return base.Channel.GetMessageStrAsync(username, password, location, from, index, count);
        }
        
        public int RemoveMessages(string username, string password, FaraPayamak.ReceiveSms.MessageLocation location, string msgIds) {
            return base.Channel.RemoveMessages(username, password, location, msgIds);
        }
        
        public System.Threading.Tasks.Task<int> RemoveMessagesAsync(string username, string password, FaraPayamak.ReceiveSms.MessageLocation location, string msgIds) {
            return base.Channel.RemoveMessagesAsync(username, password, location, msgIds);
        }
        
        public int RemoveMessages2(string username, string password, int location, string msgIds) {
            return base.Channel.RemoveMessages2(username, password, location, msgIds);
        }
        
        public System.Threading.Tasks.Task<int> RemoveMessages2Async(string username, string password, int location, string msgIds) {
            return base.Channel.RemoveMessages2Async(username, password, location, msgIds);
        }
        
        public FaraPayamak.ReceiveSms.MsgReceptions[] GetMessagesReceptions(string username, string password, int msgId, int fromRows) {
            return base.Channel.GetMessagesReceptions(username, password, msgId, fromRows);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MsgReceptions[]> GetMessagesReceptionsAsync(string username, string password, int msgId, int fromRows) {
            return base.Channel.GetMessagesReceptionsAsync(username, password, msgId, fromRows);
        }
        
        public FaraPayamak.ReceiveSms.MessagesBL[] GetMessagesAfterID(string username, string password, int location, string from, int count, int msgId) {
            return base.Channel.GetMessagesAfterID(username, password, location, from, count, msgId);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.MessagesBL[]> GetMessagesAfterIDAsync(string username, string password, int location, string from, int count, int msgId) {
            return base.Channel.GetMessagesAfterIDAsync(username, password, location, from, count, msgId);
        }
        
        public string GetMessagesAfterIDJson(string username, string password, int location, string from, int count, int msgId) {
            return base.Channel.GetMessagesAfterIDJson(username, password, location, from, count, msgId);
        }
        
        public System.Threading.Tasks.Task<string> GetMessagesAfterIDJsonAsync(string username, string password, int location, string from, int count, int msgId) {
            return base.Channel.GetMessagesAfterIDJsonAsync(username, password, location, from, count, msgId);
        }
        
        public FaraPayamak.ReceiveSms.LatestMsgReport GetLatestReceiveMsg(string username, string password, string sender, string receiver) {
            return base.Channel.GetLatestReceiveMsg(username, password, sender, receiver);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ReceiveSms.LatestMsgReport> GetLatestReceiveMsgAsync(string username, string password, string sender, string receiver) {
            return base.Channel.GetLatestReceiveMsgAsync(username, password, sender, receiver);
        }
    }
}
