// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aa_desc_in_cartableLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aa_desc_in_cartableLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201907271642470_aa_desc_in_cartableLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
