// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class surveyEntity_add_ip_user_validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(surveyEntity_add_ip_user_validation));
        
        string IMigrationMetadata.Id
        {
            get { return "201907070202374_surveyEntity_add_ip_user_validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
