// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_surveyUser_option : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_surveyUser_option));
        
        string IMigrationMetadata.Id
        {
            get { return "201907061525559_user_surveyUser_option"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
