// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _rename_commnet_to_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_rename_commnet_to_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "201909221940527__rename_commnet_to_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
