// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_idea_suggestion_cartable_relate_log_userAccess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_idea_suggestion_cartable_relate_log_userAccess));
        
        string IMigrationMetadata.Id
        {
            get { return "201907271449499_add_idea_suggestion_cartable_relate_log_userAccess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
