// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_role_permission_group_privateGroup_contactUs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_role_permission_group_privateGroup_contactUs));
        
        string IMigrationMetadata.Id
        {
            get { return "201908090749507_add_role_permission_group_privateGroup_contactUs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
