// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class answerUser_no_requared : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(answerUser_no_requared));
        
        string IMigrationMetadata.Id
        {
            get { return "201906291925130_answerUser_no_requared"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
