// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_SurveyGroupQuestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_SurveyGroupQuestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201907190941128_add_SurveyGroupQuestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
