// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_resturantDatenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_resturantDatenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001172228451_edit_resturantDatenullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
