// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _add_CheckList_PersonelofResturant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_CheckList_PersonelofResturant));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141518153__add_CheckList_PersonelofResturant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
