// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _change_ResturantPersonelRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_change_ResturantPersonelRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "202006201914255__change_ResturantPersonelRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
