// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _work_educational_background_styf_javad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_work_educational_background_styf_javad));
        
        string IMigrationMetadata.Id
        {
            get { return "202008241825231__work_educational_background_styf_javad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
