//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaraPayamak.contactSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="contactSms.ContactsSoap")]
    public interface ContactsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddGroup(string username, string password, string groupName, string Descriptions, bool showToChilds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddGroupAsync(string username, string password, string groupName, string Descriptions, bool showToChilds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.contactSms.GroupsList[] GetGroups(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.contactSms.GroupsList[]> GetGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddContact(
                    string username, 
                    string password, 
                    string groupIds, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string mobilenumber, 
                    string phone, 
                    string fax, 
                    System.DateTime birthdate, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    System.DateTime additionaldate, 
                    string additionaltext, 
                    string descriptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContact", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddContactAsync(
                    string username, 
                    string password, 
                    string groupIds, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string mobilenumber, 
                    string phone, 
                    string fax, 
                    System.DateTime birthdate, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    System.DateTime additionaldate, 
                    string additionaltext, 
                    string descriptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.contactSms.GetContactsByIDResponse GetContactsByID(FaraPayamak.contactSms.GetContactsByIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactsByID", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.contactSms.GetContactsByIDResponse> GetContactsByIDAsync(FaraPayamak.contactSms.GetContactsByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.contactSms.ContactsGridList[] GetContacts(string username, string password, int groupId, string keyword, int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.contactSms.ContactsGridList[]> GetContactsAsync(string username, string password, int groupId, string keyword, int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.contactSms.ContactEventBL[] GetContactEvents(string username, string password, int contactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.contactSms.ContactEventBL[]> GetContactEventsAsync(string username, string password, int contactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMobileExistInContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int CheckMobileExistInContact(string username, string password, string mobileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMobileExistInContact", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckMobileExistInContactAsync(string username, string password, string mobileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int ChangeContact(
                    string username, 
                    string password, 
                    int contactId, 
                    string mobilenumber, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string phone, 
                    string fax, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    string additionaltext, 
                    string descriptions, 
                    int contactStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeContact", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChangeContactAsync(
                    string username, 
                    string password, 
                    int contactId, 
                    string mobilenumber, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string phone, 
                    string fax, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    string additionaltext, 
                    string descriptions, 
                    int contactStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveContact(string username, string password, string mobilenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContact", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveContactAsync(string username, string password, string mobilenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContactByContactID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveContactByContactID(string username, string password, int contactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContactByContactID", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveContactByContactIDAsync(string username, string password, int contactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int ChangeGroup(string username, string password, int groupId, string groupName, string Descriptions, bool showToChilds, byte groupStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChangeGroupAsync(string username, string password, int groupId, string groupName, string Descriptions, bool showToChilds, byte groupStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveGroup(string username, string password, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveGroupAsync(string username, string password, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContactEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddContactEvents(string username, string password, int contactId, string eventName, byte eventType, System.DateTime eventDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContactEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddContactEventsAsync(string username, string password, int contactId, string eventName, byte eventType, System.DateTime eventDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int MergeGroups(string username, string password, int originGroupId, int destinationGroupId, bool deleteOriginGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MergeGroupsAsync(string username, string password, int originGroupId, int destinationGroupId, bool deleteOriginGroup);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupsList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int groupIDField;
        
        private int parentIdField;
        
        private int userIDField;
        
        private string groupNameField;
        
        private string groupDescriptionField;
        
        private byte groupStatusField;
        
        private int contactCountField;
        
        private bool showToChildField;
        
        private int childsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
                this.RaisePropertyChanged("GroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("ParentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GroupDescription {
            get {
                return this.groupDescriptionField;
            }
            set {
                this.groupDescriptionField = value;
                this.RaisePropertyChanged("GroupDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte GroupStatus {
            get {
                return this.groupStatusField;
            }
            set {
                this.groupStatusField = value;
                this.RaisePropertyChanged("GroupStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ContactCount {
            get {
                return this.contactCountField;
            }
            set {
                this.contactCountField = value;
                this.RaisePropertyChanged("ContactCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ShowToChild {
            get {
                return this.showToChildField;
            }
            set {
                this.showToChildField = value;
                this.RaisePropertyChanged("ShowToChild");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ChildsCount {
            get {
                return this.childsCountField;
            }
            set {
                this.childsCountField = value;
                this.RaisePropertyChanged("ChildsCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactsGridList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int contactIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nickNameField;
        
        private string corporationField;
        
        private string mobileNumbersField;
        
        private string faxNumberField;
        
        private string emailField;
        
        private byte genderField;
        
        private string descriptionsField;
        
        private System.DateTime createDateField;
        
        private string groupsField;
        
        private double creditField;
        
        private System.DateTime additionalDateField;
        
        private System.DateTime birthDateField;
        
        private int contactSortField;
        
        private byte contactStatusField;
        
        private string additionalTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
                this.RaisePropertyChanged("ContactID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
                this.RaisePropertyChanged("NickName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Corporation {
            get {
                return this.corporationField;
            }
            set {
                this.corporationField = value;
                this.RaisePropertyChanged("Corporation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MobileNumbers {
            get {
                return this.mobileNumbersField;
            }
            set {
                this.mobileNumbersField = value;
                this.RaisePropertyChanged("MobileNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("FaxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public byte Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
                this.RaisePropertyChanged("Descriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
                this.RaisePropertyChanged("Groups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("Credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime AdditionalDate {
            get {
                return this.additionalDateField;
            }
            set {
                this.additionalDateField = value;
                this.RaisePropertyChanged("AdditionalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ContactSort {
            get {
                return this.contactSortField;
            }
            set {
                this.contactSortField = value;
                this.RaisePropertyChanged("ContactSort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public byte ContactStatus {
            get {
                return this.contactStatusField;
            }
            set {
                this.contactStatusField = value;
                this.RaisePropertyChanged("ContactStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalText {
            get {
                return this.additionalTextField;
            }
            set {
                this.additionalTextField = value;
                this.RaisePropertyChanged("AdditionalText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactEventBL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactsBL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactEventBL : BaseBL {
        
        private int eventIDField;
        
        private int contactIDField;
        
        private string eventNameField;
        
        private byte eventTypeField;
        
        private System.DateTime eventDateField;
        
        private int eventDayField;
        
        private int eventMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
                this.RaisePropertyChanged("ContactID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("EventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
                this.RaisePropertyChanged("EventDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int EventDay {
            get {
                return this.eventDayField;
            }
            set {
                this.eventDayField = value;
                this.RaisePropertyChanged("EventDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int EventMonth {
            get {
                return this.eventMonthField;
            }
            set {
                this.eventMonthField = value;
                this.RaisePropertyChanged("EventMonth");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactsBL : BaseBL {
        
        private int contactIDField;
        
        private int userIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string corporationField;
        
        private string nickNameField;
        
        private string mobileNumbersField;
        
        private string phoneNumbersField;
        
        private string faxNumbersField;
        
        private System.DateTime birthDateField;
        
        private string emailField;
        
        private byte genderField;
        
        private int provinceField;
        
        private int cityField;
        
        private string addressField;
        
        private string postalCodeField;
        
        private System.DateTime additionalDateField;
        
        private string additionalTextField;
        
        private string descriptionsField;
        
        private System.DateTime createDateField;
        
        private int contactSortField;
        
        private byte contactStatusField;
        
        private double creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
                this.RaisePropertyChanged("ContactID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Corporation {
            get {
                return this.corporationField;
            }
            set {
                this.corporationField = value;
                this.RaisePropertyChanged("Corporation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
                this.RaisePropertyChanged("NickName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MobileNumbers {
            get {
                return this.mobileNumbersField;
            }
            set {
                this.mobileNumbersField = value;
                this.RaisePropertyChanged("MobileNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PhoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                this.phoneNumbersField = value;
                this.RaisePropertyChanged("PhoneNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FaxNumbers {
            get {
                return this.faxNumbersField;
            }
            set {
                this.faxNumbersField = value;
                this.RaisePropertyChanged("FaxNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public byte Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime AdditionalDate {
            get {
                return this.additionalDateField;
            }
            set {
                this.additionalDateField = value;
                this.RaisePropertyChanged("AdditionalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalText {
            get {
                return this.additionalTextField;
            }
            set {
                this.additionalTextField = value;
                this.RaisePropertyChanged("AdditionalText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
                this.RaisePropertyChanged("Descriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int ContactSort {
            get {
                return this.contactSortField;
            }
            set {
                this.contactSortField = value;
                this.RaisePropertyChanged("ContactSort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public byte ContactStatus {
            get {
                return this.contactStatusField;
            }
            set {
                this.contactStatusField = value;
                this.RaisePropertyChanged("ContactStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("Credit");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactsByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContactsByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int contactId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int status;
        
        public GetContactsByIDRequest() {
        }
        
        public GetContactsByIDRequest(string username, string password, int contactId, int status) {
            this.username = username;
            this.password = password;
            this.contactId = contactId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactsByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContactsByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FaraPayamak.contactSms.ContactsBL GetContactsByIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int status;
        
        public GetContactsByIDResponse() {
        }
        
        public GetContactsByIDResponse(FaraPayamak.contactSms.ContactsBL GetContactsByIDResult, int status) {
            this.GetContactsByIDResult = GetContactsByIDResult;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContactsSoapChannel : FaraPayamak.contactSms.ContactsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactsSoapClient : System.ServiceModel.ClientBase<FaraPayamak.contactSms.ContactsSoap>, FaraPayamak.contactSms.ContactsSoap {
        
        public ContactsSoapClient() {
        }
        
        public ContactsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddGroup(string username, string password, string groupName, string Descriptions, bool showToChilds) {
            return base.Channel.AddGroup(username, password, groupName, Descriptions, showToChilds);
        }
        
        public System.Threading.Tasks.Task<int> AddGroupAsync(string username, string password, string groupName, string Descriptions, bool showToChilds) {
            return base.Channel.AddGroupAsync(username, password, groupName, Descriptions, showToChilds);
        }
        
        public FaraPayamak.contactSms.GroupsList[] GetGroups(string username, string password) {
            return base.Channel.GetGroups(username, password);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.contactSms.GroupsList[]> GetGroupsAsync(string username, string password) {
            return base.Channel.GetGroupsAsync(username, password);
        }
        
        public int AddContact(
                    string username, 
                    string password, 
                    string groupIds, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string mobilenumber, 
                    string phone, 
                    string fax, 
                    System.DateTime birthdate, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    System.DateTime additionaldate, 
                    string additionaltext, 
                    string descriptions) {
            return base.Channel.AddContact(username, password, groupIds, firstname, lastname, nickname, corporation, mobilenumber, phone, fax, birthdate, email, gender, province, city, address, postalCode, additionaldate, additionaltext, descriptions);
        }
        
        public System.Threading.Tasks.Task<int> AddContactAsync(
                    string username, 
                    string password, 
                    string groupIds, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string mobilenumber, 
                    string phone, 
                    string fax, 
                    System.DateTime birthdate, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    System.DateTime additionaldate, 
                    string additionaltext, 
                    string descriptions) {
            return base.Channel.AddContactAsync(username, password, groupIds, firstname, lastname, nickname, corporation, mobilenumber, phone, fax, birthdate, email, gender, province, city, address, postalCode, additionaldate, additionaltext, descriptions);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FaraPayamak.contactSms.GetContactsByIDResponse FaraPayamak.contactSms.ContactsSoap.GetContactsByID(FaraPayamak.contactSms.GetContactsByIDRequest request) {
            return base.Channel.GetContactsByID(request);
        }
        
        public FaraPayamak.contactSms.ContactsBL GetContactsByID(string username, string password, int contactId, ref int status) {
            FaraPayamak.contactSms.GetContactsByIDRequest inValue = new FaraPayamak.contactSms.GetContactsByIDRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.contactId = contactId;
            inValue.status = status;
            FaraPayamak.contactSms.GetContactsByIDResponse retVal = ((FaraPayamak.contactSms.ContactsSoap)(this)).GetContactsByID(inValue);
            status = retVal.status;
            return retVal.GetContactsByIDResult;
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.contactSms.GetContactsByIDResponse> GetContactsByIDAsync(FaraPayamak.contactSms.GetContactsByIDRequest request) {
            return base.Channel.GetContactsByIDAsync(request);
        }
        
        public FaraPayamak.contactSms.ContactsGridList[] GetContacts(string username, string password, int groupId, string keyword, int from, int count) {
            return base.Channel.GetContacts(username, password, groupId, keyword, from, count);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.contactSms.ContactsGridList[]> GetContactsAsync(string username, string password, int groupId, string keyword, int from, int count) {
            return base.Channel.GetContactsAsync(username, password, groupId, keyword, from, count);
        }
        
        public FaraPayamak.contactSms.ContactEventBL[] GetContactEvents(string username, string password, int contactId) {
            return base.Channel.GetContactEvents(username, password, contactId);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.contactSms.ContactEventBL[]> GetContactEventsAsync(string username, string password, int contactId) {
            return base.Channel.GetContactEventsAsync(username, password, contactId);
        }
        
        public int CheckMobileExistInContact(string username, string password, string mobileNumber) {
            return base.Channel.CheckMobileExistInContact(username, password, mobileNumber);
        }
        
        public System.Threading.Tasks.Task<int> CheckMobileExistInContactAsync(string username, string password, string mobileNumber) {
            return base.Channel.CheckMobileExistInContactAsync(username, password, mobileNumber);
        }
        
        public int ChangeContact(
                    string username, 
                    string password, 
                    int contactId, 
                    string mobilenumber, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string phone, 
                    string fax, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    string additionaltext, 
                    string descriptions, 
                    int contactStatus) {
            return base.Channel.ChangeContact(username, password, contactId, mobilenumber, firstname, lastname, nickname, corporation, phone, fax, email, gender, province, city, address, postalCode, additionaltext, descriptions, contactStatus);
        }
        
        public System.Threading.Tasks.Task<int> ChangeContactAsync(
                    string username, 
                    string password, 
                    int contactId, 
                    string mobilenumber, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string phone, 
                    string fax, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    string additionaltext, 
                    string descriptions, 
                    int contactStatus) {
            return base.Channel.ChangeContactAsync(username, password, contactId, mobilenumber, firstname, lastname, nickname, corporation, phone, fax, email, gender, province, city, address, postalCode, additionaltext, descriptions, contactStatus);
        }
        
        public int RemoveContact(string username, string password, string mobilenumber) {
            return base.Channel.RemoveContact(username, password, mobilenumber);
        }
        
        public System.Threading.Tasks.Task<int> RemoveContactAsync(string username, string password, string mobilenumber) {
            return base.Channel.RemoveContactAsync(username, password, mobilenumber);
        }
        
        public int RemoveContactByContactID(string username, string password, int contactId) {
            return base.Channel.RemoveContactByContactID(username, password, contactId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveContactByContactIDAsync(string username, string password, int contactId) {
            return base.Channel.RemoveContactByContactIDAsync(username, password, contactId);
        }
        
        public int ChangeGroup(string username, string password, int groupId, string groupName, string Descriptions, bool showToChilds, byte groupStatus) {
            return base.Channel.ChangeGroup(username, password, groupId, groupName, Descriptions, showToChilds, groupStatus);
        }
        
        public System.Threading.Tasks.Task<int> ChangeGroupAsync(string username, string password, int groupId, string groupName, string Descriptions, bool showToChilds, byte groupStatus) {
            return base.Channel.ChangeGroupAsync(username, password, groupId, groupName, Descriptions, showToChilds, groupStatus);
        }
        
        public int RemoveGroup(string username, string password, int groupId) {
            return base.Channel.RemoveGroup(username, password, groupId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveGroupAsync(string username, string password, int groupId) {
            return base.Channel.RemoveGroupAsync(username, password, groupId);
        }
        
        public int AddContactEvents(string username, string password, int contactId, string eventName, byte eventType, System.DateTime eventDate) {
            return base.Channel.AddContactEvents(username, password, contactId, eventName, eventType, eventDate);
        }
        
        public System.Threading.Tasks.Task<int> AddContactEventsAsync(string username, string password, int contactId, string eventName, byte eventType, System.DateTime eventDate) {
            return base.Channel.AddContactEventsAsync(username, password, contactId, eventName, eventType, eventDate);
        }
        
        public int MergeGroups(string username, string password, int originGroupId, int destinationGroupId, bool deleteOriginGroup) {
            return base.Channel.MergeGroups(username, password, originGroupId, destinationGroupId, deleteOriginGroup);
        }
        
        public System.Threading.Tasks.Task<int> MergeGroupsAsync(string username, string password, int originGroupId, int destinationGroupId, bool deleteOriginGroup) {
            return base.Channel.MergeGroupsAsync(username, password, originGroupId, destinationGroupId, deleteOriginGroup);
        }
    }
}
