// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _alter_shekayat_resturantCodeName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_alter_shekayat_resturantCodeName));
        
        string IMigrationMetadata.Id
        {
            get { return "202004201510032__alter_shekayat_resturantCodeName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
