// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _add_CheckListTypeCartable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_CheckListTypeCartable));
        
        string IMigrationMetadata.Id
        {
            get { return "202002082007117__add_CheckListTypeCartable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
