// <auto-generated />
namespace SurveyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _add_resturantId_in_shekayat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_resturantId_in_shekayat));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240540449__add_resturantId_in_shekayat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
